// We don't have an API to get the states/prefectures
// instead we are using a file to store this data.

const states = {
  1: {
    en: 'Hokkaidō',
    name: '北海道',
    iso: 'JP-01',
    google_value: '1',
  },
  2: {
    en: 'Aomori',
    name: '青森県',
    iso: 'JP-02',
    google_value: '2',
  },
  3: {
    en: 'Akita',
    name: '秋田県',
    iso: 'JP-05',
    google_value: '5',
  },
  4: {
    en: 'Iwate',
    name: '岩手県',
    iso: 'JP-03',
    google_value: '3',
  },
  5: {
    en: 'Yamagata',
    name: '山形県',
    iso: 'JP-06',
    google_value: '6',
  },
  6: {
    en: 'Miyagi',
    name: '宮城県',
    iso: 'JP-04',
    google_value: '4',
  },
  7: {
    en: 'Niigata',
    name: '新潟県',
    iso: 'JP-15',
    google_value: '15',
  },
  8: {
    en: 'Fukushima',
    name: '福島県',
    iso: 'JP-07',
    google_value: '7',
  },
  9: {
    en: 'Toyama',
    name: '富山県',
    iso: 'JP-16',
    google_value: '16',
  },
  10: {
    en: 'Ishikawa',
    name: '石川県',
    iso: 'JP-17',
    google_value: '17',
  },
  11: {
    en: 'Fukui',
    name: '福井県',
    iso: 'JP-18',
    google_value: '18',
  },
  12: {
    en: 'Ibaraki',
    name: '茨城県',
    iso: 'JP-08',
    google_value: '8',
  },
  13: {
    en: 'Tochigi',
    name: '栃木県',
    iso: 'JP-09',
    google_value: '9',
  },
  14: {
    en: 'Gunma',
    name: '群馬県',
    iso: 'JP-10',
    google_value: '10',
  },
  15: {
    en: 'Nagano',
    name: '長野県',
    iso: 'JP-20',
    google_value: '20',
  },
  16: {
    en: 'Chiba',
    name: '千葉県',
    iso: 'JP-12',
    google_value: '12',
  },
  17: {
    en: 'Saitama',
    name: '埼玉県',
    iso: 'JP-11',
    google_value: '11',
  },
  18: {
    en: 'Tōkyō',
    name: '東京都',
    iso: 'JP-13',
    google_value: '13',
    grouped: true,
  },
  19: {
    en: 'Kanagawa',
    name: '神奈川県',
    iso: 'JP-14',
    google_value: '14',
  },
  20: {
    en: 'Yamanashi',
    name: '山梨県',
    iso: 'JP-19',
    google_value: '19',
  },
  21: {
    en: 'Shizuoka',
    name: '静岡県',
    iso: 'JP-22',
    google_value: '22',
  },
  22: {
    en: 'Aichi',
    name: '愛知県',
    iso: 'JP-23',
    google_value: '23',
  },
  23: {
    en: 'Gifu',
    name: '岐阜県',
    iso: 'JP-21',
    google_value: '21',
  },
  24: {
    en: 'Mie',
    name: '三重県',
    iso: 'JP-24',
    google_value: '24',
  },
  25: {
    en: 'Shiga',
    name: '滋賀県',
    iso: 'JP-25',
    google_value: '25',
  },
  26: {
    en: 'Ōsaka',
    name: '大阪府',
    iso: 'JP-27',
    google_value: '27',
    grouped: true,
  },
  27: {
    en: 'Kyōto',
    name: '京都府',
    iso: 'JP-26',
    google_value: '26',
  },
  28: {
    en: 'Nara',
    name: '奈良県',
    iso: 'JP-29',
    google_value: '29',
  },
  29: {
    en: 'Wakayama',
    name: '和歌山県',
    iso: 'JP-30',
    google_value: '30',
  },
  30: {
    en: 'Hyōgo',
    name: '兵庫県',
    iso: 'JP-28',
    google_value: '28',
  },
  31: {
    en: 'Tottori',
    name: '鳥取県',
    iso: 'JP-31',
    google_value: '31',
  },
  32: {
    en: 'Shimane',
    name: '島根県',
    iso: 'JP-32',
    google_value: '32',
  },
  33: {
    en: 'Okayama',
    name: '岡山県',
    iso: 'JP-33',
    google_value: '33',
  },
  34: {
    en: 'Hiroshima',
    name: '広島県',
    iso: 'JP-34',
    google_value: '34',
  },
  35: {
    en: 'Yamaguchi',
    name: '山口県',
    iso: 'JP-35',
    google_value: '35',
  },
  36: {
    en: 'Kagawa',
    name: '香川県',
    iso: 'JP-37',
    google_value: '37',
  },
  37: {
    en: 'Tokushima',
    name: '徳島県',
    iso: 'JP-36',
    google_value: '36',
  },
  38: {
    en: 'Kōchi',
    name: '高知県',
    iso: 'JP-39',
    google_value: '39',
  },
  39: {
    en: 'Ehime',
    name: '愛媛県',
    iso: 'JP-38',
    google_value: '38',
  },
  40: {
    en: 'Fukuoka',
    name: '福岡県',
    iso: 'JP-40',
    google_value: '40',
  },
  41: {
    en: 'Saga',
    name: '佐賀県',
    iso: 'JP-41',
    google_value: '41',
  },
  42: {
    en: 'Nagasaki',
    name: '長崎県',
    iso: 'JP-42',
    google_value: '42',
  },
  43: {
    en: 'Kumamoto',
    name: '熊本県',
    iso: 'JP-43',
    google_value: '43',
  },
  44: {
    en: 'Ōita',
    name: '大分県',
    iso: 'JP-44',
    google_value: '44',
  },
  45: {
    en: 'Miyazaki',
    name: '宮崎県',
    iso: 'JP-45',
    google_value: '45',
  },
  46: {
    en: 'Kagoshima',
    name: '鹿児島県',
    iso: 'JP-46',
    google_value: '46',
  },
  47: {
    en: 'Okinawa',
    name: '沖縄県',
    iso: 'JP-47',
    google_value: '47',
  },
};

export default states;
